#!usr/bin/php
<?php

use SimpleMigration\Application;
use SimpleMigration\Database\Connection;

require __DIR__ . '/vendor/autoload.php';

$database = require __DIR__ . '/Database/database.php';

$connection = new Connection($database);

$app = new Application($connection, $argv);
$app->run();
